// Controlled vocabularies for the onboarding pipeline form.
// Sources: `Tally wbGvKe Field Spec.md` (extracted 2026-06-10) and
// `Volunteer Onboarding Pipeline - Plan of Action.md` (decisions 2026-06-10).

export const INTENTS = ['Keep informed', 'Act now', 'Volunteer', 'Lead'] as const
export type Intent = (typeof INTENTS)[number]

export const SIGNUP_SOURCE = 'June 2026 onboarding flow'

// Shown as a "popular" group at the top of the country dropdown (plan follow-up 2).
export const POPULAR_COUNTRIES = [
	'Germany',
	'United Kingdom',
	'United States',
	'Netherlands',
	'France',
	'Brazil',
	'India',
	'Australia'
]

// Full 196-country list from the Tally form.
export const COUNTRIES = [
	'Afghanistan',
	'Albania',
	'Algeria',
	'Andorra',
	'Angola',
	'Antigua & Barbuda',
	'Argentina',
	'Armenia',
	'Australia',
	'Austria',
	'Azerbaijan',
	'Bahamas',
	'Bahrain',
	'Bangladesh',
	'Barbados',
	'Belarus',
	'Belgium',
	'Belize',
	'Benin',
	'Bhutan',
	'Bolivia',
	'Bosnia & Herzegovina',
	'Botswana',
	'Brazil',
	'Brunei',
	'Bulgaria',
	'Burkina Faso',
	'Burundi',
	'Cabo Verde',
	'Cambodia',
	'Cameroon',
	'Canada',
	'Central African Republic',
	'Chad',
	'Chile',
	'China',
	'Colombia',
	'Comoros',
	'Congo',
	'Costa Rica',
	"Côte d'Ivoire",
	'Croatia',
	'Cuba',
	'Cyprus',
	'Czech Republic',
	'Denmark',
	'Djibouti',
	'Dominica',
	'Dominican Republic',
	'DR Congo',
	'Ecuador',
	'Egypt',
	'El Salvador',
	'Equatorial Guinea',
	'Eritrea',
	'Estonia',
	'Eswatini',
	'Ethiopia',
	'Fiji',
	'Finland',
	'France',
	'Gabon',
	'Gambia',
	'Georgia',
	'Germany',
	'Ghana',
	'Greece',
	'Grenada',
	'Guatemala',
	'Guinea',
	'Guinea-Bissau',
	'Guyana',
	'Haiti',
	'Honduras',
	'Hungary',
	'Iceland',
	'India',
	'Indonesia',
	'Iran',
	'Iraq',
	'Ireland',
	'Israel',
	'Italy',
	'Jamaica',
	'Japan',
	'Jordan',
	'Kazakhstan',
	'Kenya',
	'Kiribati',
	'Kuwait',
	'Kyrgyzstan',
	'Laos',
	'Latvia',
	'Lebanon',
	'Lesotho',
	'Liberia',
	'Libya',
	'Liechtenstein',
	'Lithuania',
	'Luxembourg',
	'Madagascar',
	'Malawi',
	'Malaysia',
	'Maldives',
	'Mali',
	'Malta',
	'Marshall Islands',
	'Mauritania',
	'Mauritius',
	'Mexico',
	'Micronesia',
	'Moldova',
	'Monaco',
	'Mongolia',
	'Montenegro',
	'Morocco',
	'Mozambique',
	'Myanmar',
	'Namibia',
	'Nauru',
	'Nepal',
	'Netherlands',
	'New Zealand',
	'Nicaragua',
	'Niger',
	'Nigeria',
	'North Korea',
	'North Macedonia',
	'Norway',
	'Oman',
	'Pakistan',
	'Palau',
	'Palestine',
	'Panama',
	'Papua New Guinea',
	'Paraguay',
	'Peru',
	'Philippines',
	'Poland',
	'Portugal',
	'Qatar',
	'Romania',
	'Russia',
	'Rwanda',
	'Saint Kitts & Nevis',
	'Saint Lucia',
	'Samoa',
	'San Marino',
	'Sao Tome & Principe',
	'Saudi Arabia',
	'Senegal',
	'Serbia',
	'Seychelles',
	'Sierra Leone',
	'Singapore',
	'Slovakia',
	'Slovenia',
	'Solomon Islands',
	'Somalia',
	'South Africa',
	'South Korea',
	'South Sudan',
	'Spain',
	'Sri Lanka',
	'St. Vincent & Grenadines',
	'Sudan',
	'Suriname',
	'Sweden',
	'Switzerland',
	'Syria',
	'Taiwan',
	'Tajikistan',
	'Tanzania',
	'Thailand',
	'Timor-Leste',
	'Togo',
	'Tonga',
	'Trinidad & Tobago',
	'Tunisia',
	'Turkey',
	'Turkmenistan',
	'Tuvalu',
	'Uganda',
	'Ukraine',
	'United Arab Emirates',
	'United Kingdom',
	'United States',
	'Uruguay',
	'Uzbekistan',
	'Vanuatu',
	'Vatican City',
	'Venezuela',
	'Vietnam',
	'Yemen',
	'Zambia',
	'Zimbabwe'
]

// Languages: displayed in the language's own name, stored as the English
// canonical value (field-spec finding 10).
export const LANGUAGES: { display: string; stored: string }[] = [
	{ display: 'English', stored: 'English' },
	{ display: 'Español', stored: 'Spanish' },
	{ display: 'Français', stored: 'French' },
	{ display: 'Deutsch', stored: 'German' },
	{ display: 'Nederlands', stored: 'Dutch' },
	{ display: '中文', stored: 'Chinese' },
	{ display: '日本語', stored: 'Japanese' },
	{ display: 'हिन्दी', stored: 'Hindi' },
	{ display: 'Português', stored: 'Portuguese' },
	{ display: 'العربية', stored: 'Arabic' },
	{ display: 'Русский', stored: 'Russian' },
	{ display: 'Italiano', stored: 'Italian' },
	{ display: '한국어', stored: 'Korean' },
	{ display: 'Polski', stored: 'Polish' },
	{ display: 'Bahasa Indonesia', stored: 'Indonesian' },
	{ display: 'Türkçe', stored: 'Turkish' },
	{ display: 'Română', stored: 'Romanian' },
	{ display: 'Svenska', stored: 'Swedish' },
	{ display: 'Čeština', stored: 'Czech' },
	{ display: 'Srpski', stored: 'Serbian' },
	{ display: 'Filipino', stored: 'Filipino' },
	{ display: 'Dansk', stored: 'Danish' },
	{ display: 'Suomi', stored: 'Finnish' },
	{ display: 'עברית', stored: 'Hebrew' },
	{ display: 'Norsk', stored: 'Norwegian' },
	{ display: 'বাংলা', stored: 'Bengali' },
	{ display: 'తెలుగు', stored: 'Telugu' },
	{ display: 'தமிழ்', stored: 'Tamil' },
	{ display: 'ไทย', stored: 'Thai' },
	{ display: 'Tiếng Việt', stored: 'Vietnamese' },
	{ display: 'Other', stored: 'Other' }
]

// Tally's `Event` / `Event/Presentation` near-duplicate collapsed to one (finding 5).
export const DISCOVERY_OPTIONS = [
	'PauseAI affiliated social media',
	'Non-PauseAI affiliated social media',
	'Friend/Family referral',
	'News article',
	'Event/Presentation',
	'Internet search',
	'Other'
]

// Discovery options that reveal a "Please specify" input (kept wide, per spec's
// conditional-logic table).
export const DISCOVERY_SPECIFY_TRIGGERS = [
	'Other',
	'Event/Presentation',
	'News article',
	'Non-PauseAI affiliated social media',
	'PauseAI affiliated social media'
]

export const MOTIVATIONS = [
	'AI Safety',
	'Need for democratic oversight',
	'Ethical technology',
	'AI Governance',
	'Job Displacement',
	'Misinformation',
	'Deepfake scams and harassment',
	'Concentration of power',
	'Privacy loss',
	'Environmental damage',
	'Technology addiction',
	'Autonomous weapons',
	'Cyberattacks',
	'Bioweapons',
	'Other'
]

export const SKILLS = [
	'Software Development',
	'Video Creation',
	'Social Media Management',
	'Event Organization',
	'Public Speaking/ Presentation',
	'Writing',
	'Graphic Design/ Visual Arts',
	'Research',
	'Communications/ PR',
	'Fundraising',
	'Community Organizing',
	'Political Advocacy/ Lobbying',
	'Education/ Teaching',
	'Administrative Support',
	'Legal Knowledge',
	'Other'
]

// Tally's `10+ hours` split into two brackets, plus the support-only escape
// hatch (plan: weekly hours, 6 options).
export const WEEKLY_HOURS = [
	'Less than 3 hours',
	'3-6 hours',
	'6-10 hours',
	'10-20 hours',
	'20+ hours',
	"None — I'd rather support in other ways"
]

export const SUPPORT_ONLY_HOURS = "None — I'd rather support in other ways"
