// Controlled vocabularies for the onboarding pipeline form.

import * as m from '$lib/paraglide/messages.js'

export const INTENTS = ['Keep informed', 'Act now', 'Volunteer', 'Lead'] as const
export type Intent = (typeof INTENTS)[number]
export type IntentKey = 'act-now' | 'volunteer' | 'lead'

export const SIGNUP_SOURCE = 'June 2026 onboarding flow'

// Full 196-country list from the Tally form.
export const COUNTRIES = [
	'Afghanistan',
	'Albania',
	'Algeria',
	'Andorra',
	'Angola',
	'Antigua & Barbuda',
	'Argentina',
	'Armenia',
	'Australia',
	'Austria',
	'Azerbaijan',
	'Bahamas',
	'Bahrain',
	'Bangladesh',
	'Barbados',
	'Belarus',
	'Belgium',
	'Belize',
	'Benin',
	'Bhutan',
	'Bolivia',
	'Bosnia & Herzegovina',
	'Botswana',
	'Brazil',
	'Brunei',
	'Bulgaria',
	'Burkina Faso',
	'Burundi',
	'Cabo Verde',
	'Cambodia',
	'Cameroon',
	'Canada',
	'Central African Republic',
	'Chad',
	'Chile',
	'China',
	'Colombia',
	'Comoros',
	'Congo',
	'Costa Rica',
	"Côte d'Ivoire",
	'Croatia',
	'Cuba',
	'Cyprus',
	'Czech Republic',
	'Denmark',
	'Djibouti',
	'Dominica',
	'Dominican Republic',
	'DR Congo',
	'Ecuador',
	'Egypt',
	'El Salvador',
	'Equatorial Guinea',
	'Eritrea',
	'Estonia',
	'Eswatini',
	'Ethiopia',
	'Fiji',
	'Finland',
	'France',
	'Gabon',
	'Gambia',
	'Georgia',
	'Germany',
	'Ghana',
	'Greece',
	'Grenada',
	'Guatemala',
	'Guinea',
	'Guinea-Bissau',
	'Guyana',
	'Haiti',
	'Honduras',
	'Hungary',
	'Iceland',
	'India',
	'Indonesia',
	'Iran',
	'Iraq',
	'Ireland',
	'Israel',
	'Italy',
	'Jamaica',
	'Japan',
	'Jordan',
	'Kazakhstan',
	'Kenya',
	'Kiribati',
	'Kuwait',
	'Kyrgyzstan',
	'Laos',
	'Latvia',
	'Lebanon',
	'Lesotho',
	'Liberia',
	'Libya',
	'Liechtenstein',
	'Lithuania',
	'Luxembourg',
	'Madagascar',
	'Malawi',
	'Malaysia',
	'Maldives',
	'Mali',
	'Malta',
	'Marshall Islands',
	'Mauritania',
	'Mauritius',
	'Mexico',
	'Micronesia',
	'Moldova',
	'Monaco',
	'Mongolia',
	'Montenegro',
	'Morocco',
	'Mozambique',
	'Myanmar',
	'Namibia',
	'Nauru',
	'Nepal',
	'Netherlands',
	'New Zealand',
	'Nicaragua',
	'Niger',
	'Nigeria',
	'North Korea',
	'North Macedonia',
	'Norway',
	'Oman',
	'Pakistan',
	'Palau',
	'Palestine',
	'Panama',
	'Papua New Guinea',
	'Paraguay',
	'Peru',
	'Philippines',
	'Poland',
	'Portugal',
	'Qatar',
	'Romania',
	'Russia',
	'Rwanda',
	'Saint Kitts & Nevis',
	'Saint Lucia',
	'Samoa',
	'San Marino',
	'Sao Tome & Principe',
	'Saudi Arabia',
	'Senegal',
	'Serbia',
	'Seychelles',
	'Sierra Leone',
	'Singapore',
	'Slovakia',
	'Slovenia',
	'Solomon Islands',
	'Somalia',
	'South Africa',
	'South Korea',
	'South Sudan',
	'Spain',
	'Sri Lanka',
	'St. Vincent & Grenadines',
	'Sudan',
	'Suriname',
	'Sweden',
	'Switzerland',
	'Syria',
	'Taiwan',
	'Tajikistan',
	'Tanzania',
	'Thailand',
	'Timor-Leste',
	'Togo',
	'Tonga',
	'Trinidad & Tobago',
	'Tunisia',
	'Turkey',
	'Turkmenistan',
	'Tuvalu',
	'Uganda',
	'Ukraine',
	'United Arab Emirates',
	'United Kingdom',
	'United States',
	'Uruguay',
	'Uzbekistan',
	'Vanuatu',
	'Vatican City',
	'Venezuela',
	'Vietnam',
	'Yemen',
	'Zambia',
	'Zimbabwe'
]

// International dialing code per country, keyed by the COUNTRIES names above.
// Used to prefill the phone field's dial code from the country of residence.
export const COUNTRY_DIAL_CODES: Record<string, string> = {
	Afghanistan: '+93',
	Albania: '+355',
	Algeria: '+213',
	Andorra: '+376',
	Angola: '+244',
	'Antigua & Barbuda': '+1268',
	Argentina: '+54',
	Armenia: '+374',
	Australia: '+61',
	Austria: '+43',
	Azerbaijan: '+994',
	Bahamas: '+1242',
	Bahrain: '+973',
	Bangladesh: '+880',
	Barbados: '+1246',
	Belarus: '+375',
	Belgium: '+32',
	Belize: '+501',
	Benin: '+229',
	Bhutan: '+975',
	Bolivia: '+591',
	'Bosnia & Herzegovina': '+387',
	Botswana: '+267',
	Brazil: '+55',
	Brunei: '+673',
	Bulgaria: '+359',
	'Burkina Faso': '+226',
	Burundi: '+257',
	'Cabo Verde': '+238',
	Cambodia: '+855',
	Cameroon: '+237',
	Canada: '+1',
	'Central African Republic': '+236',
	Chad: '+235',
	Chile: '+56',
	China: '+86',
	Colombia: '+57',
	Comoros: '+269',
	Congo: '+242',
	'Costa Rica': '+506',
	"Côte d'Ivoire": '+225',
	Croatia: '+385',
	Cuba: '+53',
	Cyprus: '+357',
	'Czech Republic': '+420',
	Denmark: '+45',
	Djibouti: '+253',
	Dominica: '+1767',
	'Dominican Republic': '+1809',
	'DR Congo': '+243',
	Ecuador: '+593',
	Egypt: '+20',
	'El Salvador': '+503',
	'Equatorial Guinea': '+240',
	Eritrea: '+291',
	Estonia: '+372',
	Eswatini: '+268',
	Ethiopia: '+251',
	Fiji: '+679',
	Finland: '+358',
	France: '+33',
	Gabon: '+241',
	Gambia: '+220',
	Georgia: '+995',
	Germany: '+49',
	Ghana: '+233',
	Greece: '+30',
	Grenada: '+1473',
	Guatemala: '+502',
	Guinea: '+224',
	'Guinea-Bissau': '+245',
	Guyana: '+592',
	Haiti: '+509',
	Honduras: '+504',
	Hungary: '+36',
	Iceland: '+354',
	India: '+91',
	Indonesia: '+62',
	Iran: '+98',
	Iraq: '+964',
	Ireland: '+353',
	Israel: '+972',
	Italy: '+39',
	Jamaica: '+1876',
	Japan: '+81',
	Jordan: '+962',
	Kazakhstan: '+7',
	Kenya: '+254',
	Kiribati: '+686',
	Kuwait: '+965',
	Kyrgyzstan: '+996',
	Laos: '+856',
	Latvia: '+371',
	Lebanon: '+961',
	Lesotho: '+266',
	Liberia: '+231',
	Libya: '+218',
	Liechtenstein: '+423',
	Lithuania: '+370',
	Luxembourg: '+352',
	Madagascar: '+261',
	Malawi: '+265',
	Malaysia: '+60',
	Maldives: '+960',
	Mali: '+223',
	Malta: '+356',
	'Marshall Islands': '+692',
	Mauritania: '+222',
	Mauritius: '+230',
	Mexico: '+52',
	Micronesia: '+691',
	Moldova: '+373',
	Monaco: '+377',
	Mongolia: '+976',
	Montenegro: '+382',
	Morocco: '+212',
	Mozambique: '+258',
	Myanmar: '+95',
	Namibia: '+264',
	Nauru: '+674',
	Nepal: '+977',
	Netherlands: '+31',
	'New Zealand': '+64',
	Nicaragua: '+505',
	Niger: '+227',
	Nigeria: '+234',
	'North Korea': '+850',
	'North Macedonia': '+389',
	Norway: '+47',
	Oman: '+968',
	Pakistan: '+92',
	Palau: '+680',
	Palestine: '+970',
	Panama: '+507',
	'Papua New Guinea': '+675',
	Paraguay: '+595',
	Peru: '+51',
	Philippines: '+63',
	Poland: '+48',
	Portugal: '+351',
	Qatar: '+974',
	Romania: '+40',
	Russia: '+7',
	Rwanda: '+250',
	'Saint Kitts & Nevis': '+1869',
	'Saint Lucia': '+1758',
	Samoa: '+685',
	'San Marino': '+378',
	'Sao Tome & Principe': '+239',
	'Saudi Arabia': '+966',
	Senegal: '+221',
	Serbia: '+381',
	Seychelles: '+248',
	'Sierra Leone': '+232',
	Singapore: '+65',
	Slovakia: '+421',
	Slovenia: '+386',
	'Solomon Islands': '+677',
	Somalia: '+252',
	'South Africa': '+27',
	'South Korea': '+82',
	'South Sudan': '+211',
	Spain: '+34',
	'Sri Lanka': '+94',
	'St. Vincent & Grenadines': '+1784',
	Sudan: '+249',
	Suriname: '+597',
	Sweden: '+46',
	Switzerland: '+41',
	Syria: '+963',
	Taiwan: '+886',
	Tajikistan: '+992',
	Tanzania: '+255',
	Thailand: '+66',
	'Timor-Leste': '+670',
	Togo: '+228',
	Tonga: '+676',
	'Trinidad & Tobago': '+1868',
	Tunisia: '+216',
	Turkey: '+90',
	Turkmenistan: '+993',
	Tuvalu: '+688',
	Uganda: '+256',
	Ukraine: '+380',
	'United Arab Emirates': '+971',
	'United Kingdom': '+44',
	'United States': '+1',
	Uruguay: '+598',
	Uzbekistan: '+998',
	Vanuatu: '+678',
	'Vatican City': '+379',
	Venezuela: '+58',
	Vietnam: '+84',
	Yemen: '+967',
	Zambia: '+260',
	Zimbabwe: '+263'
}

// Languages: displayed in the language's own name, stored as the English
// canonical value (field-spec finding 10).
export const LANGUAGES: { display: string; stored: string }[] = [
	{ display: 'English', stored: 'English' },
	{ display: 'Español', stored: 'Spanish' },
	{ display: 'Français', stored: 'French' },
	{ display: 'Deutsch', stored: 'German' },
	{ display: 'Nederlands', stored: 'Dutch' },
	{ display: '中文', stored: 'Chinese' },
	{ display: '日本語', stored: 'Japanese' },
	{ display: 'हिन्दी', stored: 'Hindi' },
	{ display: 'Português', stored: 'Portuguese' },
	{ display: 'العربية', stored: 'Arabic' },
	{ display: 'Русский', stored: 'Russian' },
	{ display: 'Italiano', stored: 'Italian' },
	{ display: '한국어', stored: 'Korean' },
	{ display: 'Polski', stored: 'Polish' },
	{ display: 'Bahasa Indonesia', stored: 'Indonesian' },
	{ display: 'Türkçe', stored: 'Turkish' },
	{ display: 'Română', stored: 'Romanian' },
	{ display: 'Svenska', stored: 'Swedish' },
	{ display: 'Čeština', stored: 'Czech' },
	{ display: 'Srpski', stored: 'Serbian' },
	{ display: 'Filipino', stored: 'Filipino' },
	{ display: 'Dansk', stored: 'Danish' },
	{ display: 'Suomi', stored: 'Finnish' },
	{ display: 'עברית', stored: 'Hebrew' },
	{ display: 'Norsk', stored: 'Norwegian' },
	{ display: 'বাংলা', stored: 'Bengali' },
	{ display: 'తెలుగు', stored: 'Telugu' },
	{ display: 'தமிழ்', stored: 'Tamil' },
	{ display: 'ไทย', stored: 'Thai' },
	{ display: 'Tiếng Việt', stored: 'Vietnamese' },
	{ display: 'Other', stored: 'Other' }
]

// Tally's `Event` / `Event/Presentation` near-duplicate collapsed to one (finding 5).
export const DISCOVERY_OPTIONS = [
	'PauseAI affiliated social media',
	'Non-PauseAI affiliated social media',
	'Friend/Family referral',
	'News article',
	'Event/Presentation',
	'Internet search',
	'Other'
]

// Discovery options that reveal a "Please specify" input (kept wide, per spec's
// conditional-logic table).
export const DISCOVERY_SPECIFY_TRIGGERS = [
	'Other',
	'Event/Presentation',
	'News article',
	'Non-PauseAI affiliated social media',
	'PauseAI affiliated social media'
]

export const MOTIVATIONS = [
	'AI Safety',
	'Need for democratic oversight',
	'Ethical technology',
	'AI Governance',
	'Job Displacement',
	'Misinformation',
	'Deepfake scams and harassment',
	'Concentration of power',
	'Privacy loss',
	'Environmental damage',
	'Technology addiction',
	'Autonomous weapons',
	'Cyberattacks',
	'Bioweapons',
	'Other'
]

export const SKILLS = [
	'Software Development',
	'Video Creation',
	'Social Media Management',
	'Event Organization',
	'Public Speaking/ Presentation',
	'Writing',
	'Graphic Design/ Visual Arts',
	'Research',
	'Communications/ PR',
	'Fundraising',
	'Community Organizing',
	'Political Advocacy/ Lobbying',
	'Education/ Teaching',
	'Administrative Support',
	'Legal Knowledge',
	'Other'
]

// Tally's `10+ hours` split into two brackets (plan: weekly hours).
export const WEEKLY_HOURS = [
	'Less than 3 hours',
	'3-6 hours',
	'6-10 hours',
	'10-20 hours',
	'20+ hours'
]

export function getDiscoveryOptions(): { value: string; label: string }[] {
	return [
		{ value: 'PauseAI affiliated social media', label: m.onboarding_discovery_pauseai_social() },
		{ value: 'Non-PauseAI affiliated social media', label: m.onboarding_discovery_other_social() },
		{ value: 'Friend/Family referral', label: m.onboarding_discovery_referral() },
		{ value: 'News article', label: m.onboarding_discovery_news() },
		{ value: 'Event/Presentation', label: m.onboarding_discovery_event() },
		{ value: 'Internet search', label: m.onboarding_discovery_search() },
		{ value: 'Other', label: m.onboarding_discovery_other() }
	]
}

export function getMotivations(): { value: string; label: string }[] {
	return [
		{ value: 'AI Safety', label: m.onboarding_motivation_ai_safety() },
		{
			value: 'Need for democratic oversight',
			label: m.onboarding_motivation_democratic_oversight()
		},
		{ value: 'Ethical technology', label: m.onboarding_motivation_ethical_tech() },
		{ value: 'AI Governance', label: m.onboarding_motivation_ai_governance() },
		{ value: 'Job Displacement', label: m.onboarding_motivation_job_displacement() },
		{ value: 'Misinformation', label: m.onboarding_motivation_misinformation() },
		{ value: 'Deepfake scams and harassment', label: m.onboarding_motivation_deepfakes() },
		{ value: 'Concentration of power', label: m.onboarding_motivation_power() },
		{ value: 'Privacy loss', label: m.onboarding_motivation_privacy() },
		{ value: 'Environmental damage', label: m.onboarding_motivation_environment() },
		{ value: 'Technology addiction', label: m.onboarding_motivation_addiction() },
		{ value: 'Autonomous weapons', label: m.onboarding_motivation_weapons() },
		{ value: 'Cyberattacks', label: m.onboarding_motivation_cyber() },
		{ value: 'Bioweapons', label: m.onboarding_motivation_bioweapons() },
		{ value: 'Other', label: m.onboarding_motivation_other() }
	]
}

export function getSkills(): { value: string; label: string }[] {
	return [
		{ value: 'Software Development', label: m.onboarding_skill_software() },
		{ value: 'Video Creation', label: m.onboarding_skill_video() },
		{ value: 'Social Media Management', label: m.onboarding_skill_social_media() },
		{ value: 'Event Organization', label: m.onboarding_skill_events() },
		{ value: 'Public Speaking/ Presentation', label: m.onboarding_skill_speaking() },
		{ value: 'Writing', label: m.onboarding_skill_writing() },
		{ value: 'Graphic Design/ Visual Arts', label: m.onboarding_skill_design() },
		{ value: 'Research', label: m.onboarding_skill_research() },
		{ value: 'Communications/ PR', label: m.onboarding_skill_comms() },
		{ value: 'Fundraising', label: m.onboarding_skill_fundraising() },
		{ value: 'Community Organizing', label: m.onboarding_skill_community() },
		{ value: 'Political Advocacy/ Lobbying', label: m.onboarding_skill_advocacy() },
		{ value: 'Education/ Teaching', label: m.onboarding_skill_education() },
		{ value: 'Administrative Support', label: m.onboarding_skill_admin() },
		{ value: 'Legal Knowledge', label: m.onboarding_skill_legal() },
		{ value: 'Other', label: m.onboarding_skill_other() }
	]
}

export function getWeeklyHours(): { value: string; label: string }[] {
	return [
		{ value: 'Less than 3 hours', label: m.onboarding_hours_under_3() },
		{ value: '3-6 hours', label: m.onboarding_hours_3_6() },
		{ value: '6-10 hours', label: m.onboarding_hours_6_10() },
		{ value: '10-20 hours', label: m.onboarding_hours_10_20() },
		{ value: '20+ hours', label: m.onboarding_hours_20_plus() }
	]
}

export function getIntentOptions(): { key: IntentKey; icon: string; label: string; sub: string }[] {
	return [
		{
			key: 'act-now',
			icon: '✊',
			label: m.onboarding_intent_act_now_label(),
			sub: m.onboarding_intent_act_now_sub()
		},
		{
			key: 'volunteer',
			icon: '🤝',
			label: m.onboarding_intent_volunteer_label(),
			sub: m.onboarding_intent_volunteer_sub()
		},
		{
			key: 'lead',
			icon: '🚀',
			label: m.onboarding_intent_lead_label(),
			sub: m.onboarding_intent_lead_sub()
		}
	]
}
