create table
  public.translation (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    hash text not null,
    language_code text not null,
    translation text not null,
    path text not null,
    constraint translations_pkey primary key (id),
    constraint translations_uc_path_language_code unique (path,language_code),
    constraint translations_uc_hash_language_code unique (hash,language_code)
  ) tablespace pg_default;